#ifndef BRA_FUSED_GATE_HPP
# define BRA_FUSED_GATE_HPP

# include <bra/fused_gate/fused_hadamard.hpp>
# include <bra/fused_gate/fused_not_.hpp>
# include <bra/fused_gate/fused_pauli_x.hpp>
# include <bra/fused_gate/fused_pauli_xx.hpp>
# include <bra/fused_gate/fused_pauli_xn.hpp>
# include <bra/fused_gate/fused_pauli_y.hpp>
# include <bra/fused_gate/fused_pauli_yy.hpp>
# include <bra/fused_gate/fused_pauli_yn.hpp>
# include <bra/fused_gate/fused_pauli_z.hpp>
# include <bra/fused_gate/fused_pauli_zz.hpp>
# include <bra/fused_gate/fused_pauli_zn.hpp>
# include <bra/fused_gate/fused_swap.hpp>
# include <bra/fused_gate/fused_sqrt_pauli_x.hpp>
# include <bra/fused_gate/fused_adj_sqrt_pauli_x.hpp>
# include <bra/fused_gate/fused_sqrt_pauli_y.hpp>
# include <bra/fused_gate/fused_adj_sqrt_pauli_y.hpp>
# include <bra/fused_gate/fused_sqrt_pauli_z.hpp>
# include <bra/fused_gate/fused_adj_sqrt_pauli_z.hpp>
# include <bra/fused_gate/fused_sqrt_pauli_zz.hpp>
# include <bra/fused_gate/fused_adj_sqrt_pauli_zz.hpp>
# include <bra/fused_gate/fused_sqrt_pauli_zn.hpp>
# include <bra/fused_gate/fused_adj_sqrt_pauli_zn.hpp>
# include <bra/fused_gate/fused_u1.hpp>
# include <bra/fused_gate/fused_adj_u1.hpp>
# include <bra/fused_gate/fused_u2.hpp>
# include <bra/fused_gate/fused_adj_u2.hpp>
# include <bra/fused_gate/fused_u3.hpp>
# include <bra/fused_gate/fused_adj_u3.hpp>
# include <bra/fused_gate/fused_phase_shift.hpp>
# include <bra/fused_gate/fused_adj_phase_shift.hpp>
# include <bra/fused_gate/fused_x_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_adj_x_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_y_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_adj_y_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_controlled_v.hpp>
# include <bra/fused_gate/fused_adj_controlled_v.hpp>
# include <bra/fused_gate/fused_exponential_pauli_x.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_x.hpp>
# include <bra/fused_gate/fused_exponential_pauli_xx.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_xx.hpp>
# include <bra/fused_gate/fused_exponential_pauli_xn.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_xn.hpp>
# include <bra/fused_gate/fused_exponential_pauli_y.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_y.hpp>
# include <bra/fused_gate/fused_exponential_pauli_yy.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_yy.hpp>
# include <bra/fused_gate/fused_exponential_pauli_yn.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_yn.hpp>
# include <bra/fused_gate/fused_exponential_pauli_z.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_z.hpp>
# include <bra/fused_gate/fused_exponential_pauli_zz.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_zz.hpp>
# include <bra/fused_gate/fused_exponential_pauli_zn.hpp>
# include <bra/fused_gate/fused_adj_exponential_pauli_zn.hpp>
# include <bra/fused_gate/fused_exponential_swap.hpp>
# include <bra/fused_gate/fused_adj_exponential_swap.hpp>
# include <bra/fused_gate/fused_toffoli.hpp>
# include <bra/fused_gate/fused_controlled_hadamard.hpp>
# include <bra/fused_gate/fused_multi_controlled_hadamard.hpp>
# include <bra/fused_gate/fused_controlled_not.hpp>
# include <bra/fused_gate/fused_multi_controlled_not.hpp>
# include <bra/fused_gate/fused_controlled_pauli_x.hpp>
# include <bra/fused_gate/fused_multi_controlled_pauli_xn.hpp>
# include <bra/fused_gate/fused_controlled_pauli_y.hpp>
# include <bra/fused_gate/fused_multi_controlled_pauli_yn.hpp>
# include <bra/fused_gate/fused_controlled_pauli_z.hpp>
# include <bra/fused_gate/fused_multi_controlled_pauli_zn.hpp>
# include <bra/fused_gate/fused_multi_controlled_swap.hpp>
# include <bra/fused_gate/fused_controlled_sqrt_pauli_x.hpp>
# include <bra/fused_gate/fused_adj_controlled_sqrt_pauli_x.hpp>
# include <bra/fused_gate/fused_multi_controlled_sqrt_pauli_x.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_sqrt_pauli_x.hpp>
# include <bra/fused_gate/fused_controlled_sqrt_pauli_y.hpp>
# include <bra/fused_gate/fused_adj_controlled_sqrt_pauli_y.hpp>
# include <bra/fused_gate/fused_multi_controlled_sqrt_pauli_y.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_sqrt_pauli_y.hpp>
# include <bra/fused_gate/fused_controlled_sqrt_pauli_z.hpp>
# include <bra/fused_gate/fused_adj_controlled_sqrt_pauli_z.hpp>
# include <bra/fused_gate/fused_multi_controlled_sqrt_pauli_zn.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_sqrt_pauli_zn.hpp>
# include <bra/fused_gate/fused_controlled_phase_shift.hpp>
# include <bra/fused_gate/fused_adj_controlled_phase_shift.hpp>
# include <bra/fused_gate/fused_multi_controlled_phase_shift.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_phase_shift.hpp>
# include <bra/fused_gate/fused_controlled_u1.hpp>
# include <bra/fused_gate/fused_adj_controlled_u1.hpp>
# include <bra/fused_gate/fused_multi_controlled_u1.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_u1.hpp>
# include <bra/fused_gate/fused_controlled_u2.hpp>
# include <bra/fused_gate/fused_adj_controlled_u2.hpp>
# include <bra/fused_gate/fused_multi_controlled_u2.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_u2.hpp>
# include <bra/fused_gate/fused_controlled_u3.hpp>
# include <bra/fused_gate/fused_adj_controlled_u3.hpp>
# include <bra/fused_gate/fused_multi_controlled_u3.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_u3.hpp>
# include <bra/fused_gate/fused_controlled_x_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_adj_controlled_x_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_multi_controlled_x_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_x_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_controlled_y_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_adj_controlled_y_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_multi_controlled_y_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_y_rotation_half_pi.hpp>
# include <bra/fused_gate/fused_multi_controlled_v.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_v.hpp>
# include <bra/fused_gate/fused_controlled_exponential_pauli_x.hpp>
# include <bra/fused_gate/fused_adj_controlled_exponential_pauli_x.hpp>
# include <bra/fused_gate/fused_multi_controlled_exponential_pauli_xn.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_exponential_pauli_xn.hpp>
# include <bra/fused_gate/fused_controlled_exponential_pauli_y.hpp>
# include <bra/fused_gate/fused_adj_controlled_exponential_pauli_y.hpp>
# include <bra/fused_gate/fused_multi_controlled_exponential_pauli_yn.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_exponential_pauli_yn.hpp>
# include <bra/fused_gate/fused_controlled_exponential_pauli_z.hpp>
# include <bra/fused_gate/fused_adj_controlled_exponential_pauli_z.hpp>
# include <bra/fused_gate/fused_multi_controlled_exponential_pauli_zn.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_exponential_pauli_zn.hpp>
# include <bra/fused_gate/fused_multi_controlled_exponential_swap.hpp>
# include <bra/fused_gate/fused_adj_multi_controlled_exponential_swap.hpp>

#endif // BRA_FUSED_GATE_HPP
